== Elasticsearch Migration Helper  v2.0.4

This Elasticsearch Migration Helper plugin helps you to prepare for your
migration from Elasticsearch 2.3.x and 2.4.x to Elasticsearch 5.x. Before starting your
migration and before using this plugin, you should backup your data with
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html[snapshot/restore].

Read more about important changes in the https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking-changes-5.0.html[Breaking Changes] documentation online.

This plugin has three tools:

Cluster Checkup::

  Runs a series of checks on your cluster, nodes, and indices and alerts you
  to any known problems that need to be rectified before upgrading.

Reindex Helper::

  Indices created before v2.0.0 need to be reindexed before they can be used
  in Elasticsearch 5.x. The reindex helper upgrades old indices at the click
  of a button.

Deprecation Logging::

  Elasticsearch comes with a deprecation logger which will log a message
  whenever deprecated functionality is used. This tool enables or disables
  deprecation logging on your cluster.

IMPORTANT: It will run on Elasticsearch versions 2.3.x and 2.4.x only.

=== Installation

To install, run the following command in your Elasticsearch home directory on a *nix system:

[source,sh]
---------------
./bin/plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.4/elasticsearch-migration-2.0.4.zip
---------------

Or the equivalent on a Windows machine:

[source,sh]
---------------
.\bin\plugin install https://github.com/elastic/elasticsearch-migration/releases/download/v2.0.4/elasticsearch-migration-2.0.4.zip
---------------

=== Checking a local server

Open the following URL in your browser: http://localhost:9200/_plugin/elasticsearch-migration

=== Checking a remote cluster

The migration tool can run checks against a remote Elasticsearch cluster, as long
as the cluster has https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-http.html[CORS enabled and properly configured].

As a minimum, you will need to set the following in `elasticsearch.yml`:

[source,yaml]
-----
http.cors.enabled:      true
http.cors.allow-origin: # the hostname or a regex which matches the hostname
-----

If you use basic AUTH, you will also need to tick the `Enable basic AUTH support` checkbox and add this setting to `elasticsearch.yml`:

[source,yaml]
-----
http.cors.allow-credentials: true
-----
